Hotfix: Neuroml2 fixes.
```AttributeError: 'NML2Reader' object has no attribute 'rate_fn_map'```
This is causing failure of moose-examples: https://travis-ci.org/BhallaLab/moose-examples/jobs/436070992