Avoid open-coded strdup that cause compilation failure with new gcc
/builddir/build/BUILD/moose-3.1.3/moose-core/pymoose/moosemodule.cpp:2724:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
         strncpy(vec[currIndex].name,