Parallel solvers (#293)
* Merge bhallalab.

* Using std::copysign to get the sign of a number.

* DO NOT use round() method to get to the nearest integer. It violates
mass-conservation in small system. The probabilistic algorithm is better and
does not cause extra molecules in system.

* Force disable round() method. Fixed error message in plotutil import failure.

* Disable rounding off in reinit function.
1.2 1.2 ... 1.2
will be converted to 1.0 1.0 ..2.0... 1.0 etc. Both sequences will have
different sum sometime and will cause mass-conservation error.

* Fixed error in utility function.

* Problem is unresolvable.

* removed test logger.

* Merged upstraems and tweaks to cmake policy. Enforcing NEW by default.

* Absolute path in header.

* Show extra molecule warning when number is significant.

* Fixes to allow tests to pass under Fedora 29 (#282)

* Do not try to access position -1 in string

This ain't python ;(

* Avoid open-coded strdup that cause compilation failure with new gcc

/builddir/build/BUILD/moose-3.1.3/moose-core/pymoose/moosemodule.cpp:2724:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
         strncpy(vec[currIndex].name,

* Avoid open-coded strdup that causes a warning

/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp: In function 'int moose_Field_init(_Field*, PyObject*, PyObject*)':
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:122:12: warning: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     strncpy(name, fieldName, size);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:120:25: note: length computed here
     size_t size = strlen(fieldName);
                   ~~~~~~^~~~~~~~~~~

Add error handling while at it.

* Use single thread by default unless all benchamarking is done. For small
system, multithreaded version is costly.

* Moved utility test to tests directory.

* Enabled parallel KSolve.

* parallel solver and added a test script.

* Default behvaiour is to use serial version of both Gsolve and Ksolve.
Fixes to build system.
Needs benchmarking.

* USE 3 Threads to tests. Travis is failing because threads are not
joining. Strange!

* Added boost::thread also. No performance improvement but no seg-faults
either.

* c++11 version with std::threads. Improved performance equivalent to
boost solver.

* Run test in serial. Travis builds are timedout.

* Similar design pattern in Gsolve.

* Everything looks fine locally. Probably the timeout problem is specific
to travis.

* Very good speedup. Lets go more finescale.

* Some reformatting. Tabs to spaces by vim and tiny tweaks here and there.
Nothing logical changed.

* Faster function. But detaching muparser make everything go gaga.

* Some formatting changes.

* Don't use async even in boost case.

* Minor cleanup.

* Clean up neuroml utilities. Revered back changes which broken nml
support.

* Cleanup: removed debug related statements.

* This compiles with new API. Need benchmarking.

* Thinner wrapper around boost solvers.

* Using lambdas instead of bind. Hopefully it is even thinner.

* Some changes to test script. By default use n//2 threads.

* Great performance with gcc7.

* Disable debug build with python3.

* Prefer c++11 library function if possible.

* Gsolve now also accepts numThreads options.

* Some changes to Gsolve.

* Dsolve is multithreaded as well. It inherits number of threads from
Ksolve or Gsolve.

* Disabled MPI and NUMCORE information.

* Fixes to Parallel build with boost.

* Resolve symbolic path when searching for module in rdesigneur.

* Fixes to rdesignuer when path contains symbolic link and .
for example: /home1/dilawars/Work.SVN/PlayGround/TestMooseParallel/Sep04_check_parallel_speed/proto21.make_K_AHP()

    find('.') -> rfind('.')

* When versbose mode is set, print when a function call has ended.

* Get the GIL in PyRun process function.

* temp commit for testing on bebinca [skip ci].

* Better printing of SWC diagnostic message.

* Replaced some function calls with their faster equivalents.

* Set environment variable MOOSE_SHOW_SOLVER_PERF to show the timing info
of ksolve.

* Squashed commit of the following:

commit b6c2fad494ed9addea9ca02f12708ed21ee4d021
Author: Dilawar Singh <dilawars@ncbs.res.in>
Date:   Thu Sep 6 12:05:25 2018 +0530

    Some tweaks in printing information.

commit a7e31db58c3360916109a7ae88f9701ff589727f
Author: Dilawar Singh <dilawars@ncbs.res.in>
Date:   Thu Sep 6 11:14:33 2018 +0530

    Tweaks in printing diagnostics.

commit c43b89018806d1d67c335e03ea7c245804ffd4da
Author: Dilawar Singh <dilawars@ncbs.res.in>
Date:   Thu Sep 6 10:24:12 2018 +0530

    Added a map to keep the time and steps taken by Ksolve and Hsolve.

commit c6ee187cee2659b20dfe7f512651915a9d94f6eb
Author: Dilawar Singh <dilawars@ncbs.res.in>
Date:   Wed Sep 5 18:34:57 2018 +0530

    HSolve will also show the time taken.

* Rdesigneur fixes from master branch.

* Fixed a macro and removed debug message.

* Dsolve is serial again. updateJunction can not be parallelized since it
both reads and update the value of either side of voxelpool inside a for loop.

* Use fixXreacs from moose. Removed the local copy.

* Added test for dsolve and gsolve together.