Fixes to allow tests to pass under Fedora 29 (#282)
* Do not try to access position -1 in string

This ain't python ;(

* Avoid open-coded strdup that cause compilation failure with new gcc

/builddir/build/BUILD/moose-3.1.3/moose-core/pymoose/moosemodule.cpp:2724:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
         strncpy(vec[currIndex].name,

* Avoid open-coded strdup that causes a warning

/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp: In function 'int moose_Field_init(_Field*, PyObject*, PyObject*)':
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:122:12: warning: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     strncpy(name, fieldName, size);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:120:25: note: length computed here
     size_t size = strlen(fieldName);
                   ~~~~~~^~~~~~~~~~~

Add error handling while at it.