Test xreacs (#287)
* Merge bhallalab.

* Using std::copysign to get the sign of a number.

* DO NOT use round() method to get to the nearest integer. It violates
mass-conservation in small system. The probabilistic algorithm is better and
does not cause extra molecules in system.

* Force disable round() method. Fixed error message in plotutil import failure.

* Disable rounding off in reinit function.
1.2 1.2 ... 1.2
will be converted to 1.0 1.0 ..2.0... 1.0 etc. Both sequences will have
different sum sometime and will cause mass-conservation error.

* Fixed error in utility function.

* Problem is unresolvable.

* removed test logger.

* Merged upstraems and tweaks to cmake policy. Enforcing NEW by default.

* Absolute path in header.

* Show extra molecule warning when number is significant.

* Fixes to allow tests to pass under Fedora 29 (#282)

* Do not try to access position -1 in string

This ain't python ;(

* Avoid open-coded strdup that cause compilation failure with new gcc

/builddir/build/BUILD/moose-3.1.3/moose-core/pymoose/moosemodule.cpp:2724:32: error: invalid conversion from 'const char*' to 'char*' [-fpermissive]
         strncpy(vec[currIndex].name,

* Avoid open-coded strdup that causes a warning

/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp: In function 'int moose_Field_init(_Field*, PyObject*, PyObject*)':
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:122:12: warning: 'char* strncpy(char*, const char*, size_t)' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     strncpy(name, fieldName, size);
     ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
/home/zbyszek/python/moose/moose-core/pymoose/mfield.cpp:120:25: note: length computed here
     size_t size = strlen(fieldName);
                   ~~~~~~^~~~~~~~~~~

Add error handling while at it.

* Use single thread by default unless all benchamarking is done. For small
system, multithreaded version is costly.

* Added test-suite for Xreads from Upi.

* Enabled tests.

* Some cleanup in tests.
DO not position EndoMesh.

* Added new tests from Upi.

* Test each script separately.

* Save the file in all tests.

* Fixes to filenames.

* Added tests.

* Moved utility test to tests directory.

* test_xreacs suite is now passing.

* Removed temp tests.

* Disable matplotlib from tests.

* Test was failing with boost with 5e-5 tolerance. Increased it to 6e-5
and now everything is fine.