This is now a working version of the repository, but I cannot guarantee that it will compile on all the platforms it should. Stuff for this version: Various improvements to the preprocessor.         - Can put lines into the private portions of the *Wrapper.h                 file (previously only .h was possible).         - Can put lines into the *Wrapper.cpp file. Compilation fixes for Ubuntu 6.06. Unfortunately some of these involve         hacking the output files from the parser. A make clean would not work.         Because these are parser output files they are not managed by SVN.         The fixes are listed below. Lots of work on the solver for biochemical kinetics.         Stoichiometry matrix works.         Grabbing the state of the model works         An API for connecting a numerical engine to the Stoich class works.         A ForwardEuler numerical engine (purely for demonstration) works.         The beginnings of the Ksolve object compile, but it is not         functional.  Ksolve will do the actual zombification of the model         objects. At this stage it successfully takes over the Process         function of molecules, but does not go on to handle forwarding         of calls and assignments.         The test directory has a number of new test files for the Stoich         and ForwardEuler classes.
Compiler flags and other fixes to get compilation on
        g++ (GCC) 4.0.3 (Ubuntu 4.0.3-1ubuntu5)

- Here are the compiler flags that eliminate most errors:
             -DYYMALLOC -DYYFREE

- Here are the remaining error messages:

/usr/include/FlexLexer.h:113: error: redefinition of ‘class yyFlexLexer’
/usr/include/FlexLexer.h:113: error: previous definition of ‘class
yyFlexLexer’
GenesisParser.yy.cpp:1850: error: declaration of ‘int isatty(int)’ throws
different exceptions
/usr/include/unistd.h:717: error: than previous declaration ‘int
isatty(int) throw ()’
GenesisParser.tab.cpp: In member function ‘int myFlexLexer::yyparse()’:
GenesisParser.tab.cpp:2756: error: ‘1’ cannot be used as a function
make[1]: *** [GenesisParser.tab.o] Error 1

The first error (line 113) is fixed if we comment out this line:

GenesisParser.yy.cpp:20
    #define yyFlexLexer yyFlexLexer

(yes, it seems like an incredibly dumb line)

The second error (1850) goes away if we comment out the declaration
The third error (2756) goes away if 2755 and 2756 lines are commented out.



git-svn-id: https://svn.code.sf.net/p/moose/code/moose/trunk@3 d1858a74-f715-0410-99c9-c66fe9cce3d6

Former-commit-id: 07be7a8af7b6e284f565cdb98cf1d34ddb3c47ff